### ISSUE TITLE
suggest upgrade fixed PHP version to 7.1 or higher 

### ISSUE THREAD

**Issue by dongm2ez** [cronitorio/cronitor-php#31]
https://github.com/cronitorio/cronitor-php/blob/9da228042608af014f9819dc020450c243ffc42f/lib/Client.php#L7-L9

The visibility of these constants is only available in PHP 7.1.

**Comment by seanmcoleman** [comment]
@dongm2ez just to make sure I understand correctly, are you suggesting that the `const` keyword is only available since PHP 7.1? Or are you pointing to the scoping modifier `private`? 

All my research states that `const` was introduced in 5.3 and array declarations are supported as of 5.6. I could certainly be mistaken though.

Generally speaking, we want to keep broad PHP support since the library doesn't have hard dependencies on anything that requires 7.1. It'd be great to instead adjust the code to be compliant with PHP 5.6, if necessary. 

Thanks in advance for clarifying for us! cc @aflanagan

**Comment by dongm2ez** [comment]
@seanmcoleman I point to the scoping modifier `private`, this feature adds in PHP7.1, this is the reference https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.class-constant-visibility

**Comment by seanmcoleman** [comment]
Thanks @dongm2ez, that totally makes sense and the link is much appreciated! Instead of upgrading the required PHP version, I was thinking there'd be more benefit to keeping wider compatibility than the constant modifiers. Would you mind just removing `private` from these instead of the version bump?

**Comment by dongm2ez** [comment]
received your suggestion, and it was revised.
